
// This file has been generated by the GUI designer. Do not modify.
namespace Proyecto
{
	public partial class BebidasFriasView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Proyecto.BebidasFriasView
			this.Name = "Proyecto.BebidasFriasView";
			this.Title = global::Mono.Unix.Catalog.GetString ("BebidasFriasView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
