
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Label total;
	private global::Gtk.Table table2;
	private global::Gtk.Button botonticket;
	private global::Gtk.Button buttonNuevoPedido;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Table table1;
	private global::Gtk.Button botonBebidasFrias;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	private global::Gtk.Button button4;
	private global::Gtk.Button button5;
	private global::Gtk.Button button6;
	private global::Gtk.Button button7;
	private global::Gtk.Button button8;
	private global::Gtk.Button button9;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Cafetería Torroners - Inicio");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
		this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.vbox1.Add (this.fixed4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed4]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(5));
		// Container child vbox1.Gtk.Box+BoxChild
		this.total = new global::Gtk.Label ();
		this.total.Name = "total";
		this.total.Xalign = 1F;
		this.total.LabelProp = global::Mono.Unix.Catalog.GetString ("Total:");
		this.total.Wrap = true;
		this.total.Justify = ((global::Gtk.Justification)(1));
		this.vbox1.Add (this.total);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.total]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(4)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.botonticket = new global::Gtk.Button ();
		this.botonticket.CanFocus = true;
		this.botonticket.Name = "botonticket";
		this.botonticket.UseUnderline = true;
		// Container child botonticket.Gtk.Container+ContainerChild
		global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w4 = new global::Gtk.HBox ();
		w4.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w5 = new global::Gtk.Image ();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
		w4.Add (w5);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.LabelProp = global::Mono.Unix.Catalog.GetString ("TICKET");
		w7.UseUnderline = true;
		w4.Add (w7);
		w3.Add (w4);
		this.botonticket.Add (w3);
		this.table2.Add (this.botonticket);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.botonticket]));
		w11.LeftAttach = ((uint)(3));
		w11.RightAttach = ((uint)(4));
		w11.XOptions = ((global::Gtk.AttachOptions)(0));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonNuevoPedido = new global::Gtk.Button ();
		this.buttonNuevoPedido.CanFocus = true;
		this.buttonNuevoPedido.Name = "buttonNuevoPedido";
		this.buttonNuevoPedido.UseUnderline = true;
		// Container child buttonNuevoPedido.Gtk.Container+ContainerChild
		global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w13 = new global::Gtk.HBox ();
		w13.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w14 = new global::Gtk.Image ();
		w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-file", global::Gtk.IconSize.Menu);
		w13.Add (w14);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w16 = new global::Gtk.Label ();
		w16.LabelProp = global::Mono.Unix.Catalog.GetString ("INICIAR PEDIDO");
		w16.UseUnderline = true;
		w13.Add (w16);
		w12.Add (w13);
		this.buttonNuevoPedido.Add (w12);
		this.table2.Add (this.buttonNuevoPedido);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonNuevoPedido]));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.table2.Add (this.fixed2);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed2]));
		w21.LeftAttach = ((uint)(2));
		w21.RightAttach = ((uint)(3));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.table2.Add (this.fixed3);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed3]));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.vbox1.Add (this.fixed1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		w24.Padding = ((uint)(1));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
		w25.Position = 4;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.botonBebidasFrias = new global::Gtk.Button ();
		this.botonBebidasFrias.CanFocus = true;
		this.botonBebidasFrias.Name = "botonBebidasFrias";
		this.botonBebidasFrias.UseUnderline = true;
		this.botonBebidasFrias.Label = global::Mono.Unix.Catalog.GetString ("Bebidas Frías");
		this.table1.Add (this.botonBebidasFrias);
		// Container child table1.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Bebidas Calientes");
		this.table1.Add (this.button2);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.button2]));
		w27.LeftAttach = ((uint)(1));
		w27.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Bocadillos");
		this.table1.Add (this.button3);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.button3]));
		w28.LeftAttach = ((uint)(2));
		w28.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Almuerzo Parte");
		this.table1.Add (this.button4);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.button4]));
		w29.TopAttach = ((uint)(1));
		w29.BottomAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Almuerzo Completo");
		this.table1.Add (this.button5);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.button5]));
		w30.TopAttach = ((uint)(1));
		w30.BottomAttach = ((uint)(2));
		w30.LeftAttach = ((uint)(1));
		w30.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Desayuno Popular");
		this.table1.Add (this.button6);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.button6]));
		w31.TopAttach = ((uint)(1));
		w31.BottomAttach = ((uint)(2));
		w31.LeftAttach = ((uint)(2));
		w31.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("Bollería Dulce");
		this.table1.Add (this.button7);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.button7]));
		w32.TopAttach = ((uint)(2));
		w32.BottomAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button ();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("Bollería Salada");
		this.table1.Add (this.button8);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.button8]));
		w33.TopAttach = ((uint)(2));
		w33.BottomAttach = ((uint)(3));
		w33.LeftAttach = ((uint)(1));
		w33.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button ();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("Ayuda");
		this.table1.Add (this.button9);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.button9]));
		w34.TopAttach = ((uint)(2));
		w34.BottomAttach = ((uint)(3));
		w34.LeftAttach = ((uint)(2));
		w34.RightAttach = ((uint)(3));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w35.Position = 5;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 702;
		this.DefaultHeight = 501;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonNuevoPedido.Clicked += new global::System.EventHandler (this.OnButtonNuevoPedidoClicked);
		this.botonticket.Clicked += new global::System.EventHandler (this.OnBotonticketClicked);
		this.button9.Clicked += new global::System.EventHandler (this.OnButton9Clicked);
		this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
		this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
		this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.botonBebidasFrias.Clicked += new global::System.EventHandler (this.OnBotonBebidasFriasClicked);
	}
}
