
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoCafeteria
{
	public partial class BolleriaDulceView
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label labelBolleriaDulce;
		private global::Gtk.Fixed fixed17;
		private global::Gtk.ScrolledWindow scrolledwindow3;
		private global::Gtk.TreeView treeView;
		private global::Gtk.Table table3;
		private global::Gtk.Button botonAceptar;
		private global::Gtk.Button botonAtras;
		private global::Gtk.Button botonEliminar;
		private global::Gtk.Fixed fixed18;
		private global::Gtk.Fixed fixed19;
		private global::Gtk.Fixed fixed20;
		private global::Gtk.Fixed fixed21;
		private global::Gtk.Fixed fixed22;
		private global::Gtk.Fixed fixed23;
		private global::Gtk.Fixed fixed24;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoCafeteria.BolleriaDulceView
			this.Name = "ProyectoCafeteria.BolleriaDulceView";
			this.Title = global::Mono.Unix.Catalog.GetString ("BolleriaDulceView");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child ProyectoCafeteria.BolleriaDulceView.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelBolleriaDulce = new global::Gtk.Label ();
			this.labelBolleriaDulce.Name = "labelBolleriaDulce";
			this.labelBolleriaDulce.LabelProp = global::Mono.Unix.Catalog.GetString ("labelBolleriaDulce");
			this.vbox3.Add (this.labelBolleriaDulce);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelBolleriaDulce]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed17 = new global::Gtk.Fixed ();
			this.fixed17.Name = "fixed17";
			this.fixed17.HasWindow = false;
			this.vbox3.Add (this.fixed17);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed17]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView ();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.scrolledwindow3.Add (this.treeView);
			this.vbox3.Add (this.scrolledwindow3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scrolledwindow3]));
			w4.Position = 2;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(5)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.botonAceptar = new global::Gtk.Button ();
			this.botonAceptar.CanFocus = true;
			this.botonAceptar.Name = "botonAceptar";
			this.botonAceptar.UseUnderline = true;
			// Container child botonAceptar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w6 = new global::Gtk.HBox ();
			w6.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w6.Add (w7);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w9 = new global::Gtk.Label ();
			w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
			w9.UseUnderline = true;
			w6.Add (w9);
			w5.Add (w6);
			this.botonAceptar.Add (w5);
			this.table3.Add (this.botonAceptar);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.botonAceptar]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.botonAtras = new global::Gtk.Button ();
			this.botonAtras.CanFocus = true;
			this.botonAtras.Name = "botonAtras";
			this.botonAtras.UseUnderline = true;
			// Container child botonAtras.Gtk.Container+ContainerChild
			global::Gtk.Alignment w14 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w15 = new global::Gtk.HBox ();
			w15.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-home", global::Gtk.IconSize.Menu);
			w15.Add (w16);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w18 = new global::Gtk.Label ();
			w18.LabelProp = global::Mono.Unix.Catalog.GetString ("Atras");
			w18.UseUnderline = true;
			w15.Add (w18);
			w14.Add (w15);
			this.botonAtras.Add (w14);
			this.table3.Add (this.botonAtras);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.botonAtras]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.botonEliminar = new global::Gtk.Button ();
			this.botonEliminar.CanFocus = true;
			this.botonEliminar.Name = "botonEliminar";
			this.botonEliminar.UseUnderline = true;
			// Container child botonEliminar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w23 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w24 = new global::Gtk.HBox ();
			w24.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w25 = new global::Gtk.Image ();
			w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w24.Add (w25);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w27 = new global::Gtk.Label ();
			w27.LabelProp = global::Mono.Unix.Catalog.GetString ("Eliminar");
			w27.UseUnderline = true;
			w24.Add (w27);
			w23.Add (w24);
			this.botonEliminar.Add (w23);
			this.table3.Add (this.botonEliminar);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3 [this.botonEliminar]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.LeftAttach = ((uint)(4));
			w31.RightAttach = ((uint)(5));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed18 = new global::Gtk.Fixed ();
			this.fixed18.Name = "fixed18";
			this.fixed18.HasWindow = false;
			this.table3.Add (this.fixed18);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed18]));
			w32.LeftAttach = ((uint)(4));
			w32.RightAttach = ((uint)(5));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed19 = new global::Gtk.Fixed ();
			this.fixed19.Name = "fixed19";
			this.fixed19.HasWindow = false;
			this.table3.Add (this.fixed19);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed19]));
			w33.LeftAttach = ((uint)(3));
			w33.RightAttach = ((uint)(4));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed20 = new global::Gtk.Fixed ();
			this.fixed20.Name = "fixed20";
			this.fixed20.HasWindow = false;
			this.table3.Add (this.fixed20);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed20]));
			w34.LeftAttach = ((uint)(2));
			w34.RightAttach = ((uint)(3));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed21 = new global::Gtk.Fixed ();
			this.fixed21.Name = "fixed21";
			this.fixed21.HasWindow = false;
			this.table3.Add (this.fixed21);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed21]));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed22 = new global::Gtk.Fixed ();
			this.fixed22.Name = "fixed22";
			this.fixed22.HasWindow = false;
			this.table3.Add (this.fixed22);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed22]));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed23 = new global::Gtk.Fixed ();
			this.fixed23.Name = "fixed23";
			this.fixed23.HasWindow = false;
			this.table3.Add (this.fixed23);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed23]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed24 = new global::Gtk.Fixed ();
			this.fixed24.Name = "fixed24";
			this.fixed24.HasWindow = false;
			this.table3.Add (this.fixed24);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed24]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table3);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table3]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 558;
			this.DefaultHeight = 391;
			this.Show ();
			this.treeView.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeViewRowActivated);
			this.botonEliminar.Clicked += new global::System.EventHandler (this.OnBotonEliminarClicked);
			this.botonAtras.Clicked += new global::System.EventHandler (this.OnBotonAtrasClicked);
			this.botonAceptar.Clicked += new global::System.EventHandler (this.OnBotonAceptarClicked);
		}
	}
}
