
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoCafeteria
{
	public partial class BolleriaSaladaView
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label labelBolleriaSalada;
		private global::Gtk.Fixed fixed25;
		private global::Gtk.ScrolledWindow scrolledwindow4;
		private global::Gtk.TreeView treeView;
		private global::Gtk.Table table4;
		private global::Gtk.Button botonAceptar;
		private global::Gtk.Button botonAtras;
		private global::Gtk.Button botonEliminar;
		private global::Gtk.Fixed fixed26;
		private global::Gtk.Fixed fixed27;
		private global::Gtk.Fixed fixed28;
		private global::Gtk.Fixed fixed29;
		private global::Gtk.Fixed fixed30;
		private global::Gtk.Fixed fixed31;
		private global::Gtk.Fixed fixed32;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoCafeteria.BolleriaSaladaView
			this.Name = "ProyectoCafeteria.BolleriaSaladaView";
			this.Title = global::Mono.Unix.Catalog.GetString ("BolleriaSaladaView");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child ProyectoCafeteria.BolleriaSaladaView.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelBolleriaSalada = new global::Gtk.Label ();
			this.labelBolleriaSalada.Name = "labelBolleriaSalada";
			this.labelBolleriaSalada.LabelProp = global::Mono.Unix.Catalog.GetString ("labelBolleriaSalada");
			this.vbox4.Add (this.labelBolleriaSalada);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelBolleriaSalada]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed25 = new global::Gtk.Fixed ();
			this.fixed25.Name = "fixed25";
			this.fixed25.HasWindow = false;
			this.vbox4.Add (this.fixed25);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed25]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow4.CanFocus = true;
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow4.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView ();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.scrolledwindow4.Add (this.treeView);
			this.vbox4.Add (this.scrolledwindow4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scrolledwindow4]));
			w4.Position = 2;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table (((uint)(2)), ((uint)(5)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.botonAceptar = new global::Gtk.Button ();
			this.botonAceptar.CanFocus = true;
			this.botonAceptar.Name = "botonAceptar";
			this.botonAceptar.UseUnderline = true;
			// Container child botonAceptar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w6 = new global::Gtk.HBox ();
			w6.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w6.Add (w7);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w9 = new global::Gtk.Label ();
			w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
			w9.UseUnderline = true;
			w6.Add (w9);
			w5.Add (w6);
			this.botonAceptar.Add (w5);
			this.table4.Add (this.botonAceptar);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4 [this.botonAceptar]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.botonAtras = new global::Gtk.Button ();
			this.botonAtras.CanFocus = true;
			this.botonAtras.Name = "botonAtras";
			this.botonAtras.UseUnderline = true;
			// Container child botonAtras.Gtk.Container+ContainerChild
			global::Gtk.Alignment w14 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w15 = new global::Gtk.HBox ();
			w15.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-home", global::Gtk.IconSize.Menu);
			w15.Add (w16);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w18 = new global::Gtk.Label ();
			w18.LabelProp = global::Mono.Unix.Catalog.GetString ("Atras");
			w18.UseUnderline = true;
			w15.Add (w18);
			w14.Add (w15);
			this.botonAtras.Add (w14);
			this.table4.Add (this.botonAtras);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table4 [this.botonAtras]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.botonEliminar = new global::Gtk.Button ();
			this.botonEliminar.CanFocus = true;
			this.botonEliminar.Name = "botonEliminar";
			this.botonEliminar.UseUnderline = true;
			// Container child botonEliminar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w23 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w24 = new global::Gtk.HBox ();
			w24.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w25 = new global::Gtk.Image ();
			w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w24.Add (w25);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w27 = new global::Gtk.Label ();
			w27.LabelProp = global::Mono.Unix.Catalog.GetString ("Eliminar");
			w27.UseUnderline = true;
			w24.Add (w27);
			w23.Add (w24);
			this.botonEliminar.Add (w23);
			this.table4.Add (this.botonEliminar);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table4 [this.botonEliminar]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.LeftAttach = ((uint)(4));
			w31.RightAttach = ((uint)(5));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed26 = new global::Gtk.Fixed ();
			this.fixed26.Name = "fixed26";
			this.fixed26.HasWindow = false;
			this.table4.Add (this.fixed26);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed26]));
			w32.LeftAttach = ((uint)(4));
			w32.RightAttach = ((uint)(5));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed27 = new global::Gtk.Fixed ();
			this.fixed27.Name = "fixed27";
			this.fixed27.HasWindow = false;
			this.table4.Add (this.fixed27);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed27]));
			w33.LeftAttach = ((uint)(3));
			w33.RightAttach = ((uint)(4));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed28 = new global::Gtk.Fixed ();
			this.fixed28.Name = "fixed28";
			this.fixed28.HasWindow = false;
			this.table4.Add (this.fixed28);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed28]));
			w34.LeftAttach = ((uint)(2));
			w34.RightAttach = ((uint)(3));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed29 = new global::Gtk.Fixed ();
			this.fixed29.Name = "fixed29";
			this.fixed29.HasWindow = false;
			this.table4.Add (this.fixed29);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed29]));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed30 = new global::Gtk.Fixed ();
			this.fixed30.Name = "fixed30";
			this.fixed30.HasWindow = false;
			this.table4.Add (this.fixed30);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed30]));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed31 = new global::Gtk.Fixed ();
			this.fixed31.Name = "fixed31";
			this.fixed31.HasWindow = false;
			this.table4.Add (this.fixed31);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed31]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed32 = new global::Gtk.Fixed ();
			this.fixed32.Name = "fixed32";
			this.fixed32.HasWindow = false;
			this.table4.Add (this.fixed32);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed32]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add (this.table4);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table4]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 638;
			this.DefaultHeight = 442;
			this.Show ();
			this.treeView.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeViewRowActivated);
			this.botonEliminar.Clicked += new global::System.EventHandler (this.OnBotonEliminarClicked);
			this.botonAtras.Clicked += new global::System.EventHandler (this.OnBotonAtrasClicked);
			this.botonAceptar.Clicked += new global::System.EventHandler (this.OnBotonAceptarClicked);
		}
	}
}
