
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoCafeteria
{
	public partial class ImprimirTicket
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.Fixed fixed125;
		private global::Gtk.Table table12;
		private global::Gtk.Fixed fixed131;
		private global::Gtk.Fixed fixed132;
		private global::Gtk.Fixed fixed133;
		private global::Gtk.Fixed fixed134;
		private global::Gtk.Fixed fixed135;
		private global::Gtk.Fixed fixed136;
		private global::Gtk.Fixed fixed137;
		private global::Gtk.Fixed fixed138;
		private global::Gtk.Fixed fixed139;
		private global::Gtk.Fixed fixed140;
		private global::Gtk.Image image80;
		private global::Gtk.Label labelMsg1;
		private global::Gtk.Fixed fixed124;
		private global::Gtk.Table table13;
		private global::Gtk.Fixed fixed141;
		private global::Gtk.Fixed fixed142;
		private global::Gtk.Fixed fixed143;
		private global::Gtk.Fixed fixed144;
		private global::Gtk.Fixed fixed145;
		private global::Gtk.Fixed fixed146;
		private global::Gtk.Fixed fixed147;
		private global::Gtk.Fixed fixed148;
		private global::Gtk.Fixed fixed149;
		private global::Gtk.Fixed fixed150;
		private global::Gtk.Fixed fixed151;
		private global::Gtk.Fixed fixed152;
		private global::Gtk.Fixed fixed153;
		private global::Gtk.Fixed fixed154;
		private global::Gtk.Label labelMsg2;
		private global::Gtk.Table table14;
		private global::Gtk.Button botonAceptar;
		private global::Gtk.Fixed fixed155;
		private global::Gtk.Fixed fixed156;
		private global::Gtk.Fixed fixed157;
		private global::Gtk.Fixed fixed158;
		private global::Gtk.Fixed fixed159;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoCafeteria.ImprimirTicket
			this.Name = "ProyectoCafeteria.ImprimirTicket";
			this.Title = global::Mono.Unix.Catalog.GetString ("ImprimirTicket");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			// Container child ProyectoCafeteria.ImprimirTicket.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.fixed125 = new global::Gtk.Fixed ();
			this.fixed125.Name = "fixed125";
			this.fixed125.HasWindow = false;
			this.vbox7.Add (this.fixed125);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed125]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table12 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table12.Name = "table12";
			this.table12.RowSpacing = ((uint)(6));
			this.table12.ColumnSpacing = ((uint)(6));
			// Container child table12.Gtk.Table+TableChild
			this.fixed131 = new global::Gtk.Fixed ();
			this.fixed131.Name = "fixed131";
			this.fixed131.HasWindow = false;
			this.table12.Add (this.fixed131);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed131]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed132 = new global::Gtk.Fixed ();
			this.fixed132.Name = "fixed132";
			this.fixed132.HasWindow = false;
			this.table12.Add (this.fixed132);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed132]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed133 = new global::Gtk.Fixed ();
			this.fixed133.Name = "fixed133";
			this.fixed133.HasWindow = false;
			this.table12.Add (this.fixed133);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed133]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed134 = new global::Gtk.Fixed ();
			this.fixed134.Name = "fixed134";
			this.fixed134.HasWindow = false;
			this.table12.Add (this.fixed134);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed134]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(3));
			w5.RightAttach = ((uint)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed135 = new global::Gtk.Fixed ();
			this.fixed135.Name = "fixed135";
			this.fixed135.HasWindow = false;
			this.table12.Add (this.fixed135);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed135]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed136 = new global::Gtk.Fixed ();
			this.fixed136.Name = "fixed136";
			this.fixed136.HasWindow = false;
			this.table12.Add (this.fixed136);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed136]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed137 = new global::Gtk.Fixed ();
			this.fixed137.Name = "fixed137";
			this.fixed137.HasWindow = false;
			this.table12.Add (this.fixed137);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed137]));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed138 = new global::Gtk.Fixed ();
			this.fixed138.Name = "fixed138";
			this.fixed138.HasWindow = false;
			this.table12.Add (this.fixed138);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed138]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed139 = new global::Gtk.Fixed ();
			this.fixed139.Name = "fixed139";
			this.fixed139.HasWindow = false;
			this.table12.Add (this.fixed139);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed139]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.fixed140 = new global::Gtk.Fixed ();
			this.fixed140.Name = "fixed140";
			this.fixed140.HasWindow = false;
			this.table12.Add (this.fixed140);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table12 [this.fixed140]));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.image80 = new global::Gtk.Image ();
			this.image80.Name = "image80";
			this.image80.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Dialog);
			this.table12.Add (this.image80);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table12 [this.image80]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.labelMsg1 = new global::Gtk.Label ();
			this.labelMsg1.Name = "labelMsg1";
			this.labelMsg1.LabelProp = global::Mono.Unix.Catalog.GetString ("Su ticket ha sido impreso.\nPara pagar, pase por caja.");
			this.table12.Add (this.labelMsg1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table12 [this.labelMsg1]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table12);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table12]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.fixed124 = new global::Gtk.Fixed ();
			this.fixed124.Name = "fixed124";
			this.fixed124.HasWindow = false;
			this.vbox7.Add (this.fixed124);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed124]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table13 = new global::Gtk.Table (((uint)(3)), ((uint)(5)), false);
			this.table13.Name = "table13";
			this.table13.RowSpacing = ((uint)(6));
			this.table13.ColumnSpacing = ((uint)(6));
			// Container child table13.Gtk.Table+TableChild
			this.fixed141 = new global::Gtk.Fixed ();
			this.fixed141.Name = "fixed141";
			this.fixed141.HasWindow = false;
			this.table13.Add (this.fixed141);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed141]));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed142 = new global::Gtk.Fixed ();
			this.fixed142.Name = "fixed142";
			this.fixed142.HasWindow = false;
			this.table13.Add (this.fixed142);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed142]));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed143 = new global::Gtk.Fixed ();
			this.fixed143.Name = "fixed143";
			this.fixed143.HasWindow = false;
			this.table13.Add (this.fixed143);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed143]));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed144 = new global::Gtk.Fixed ();
			this.fixed144.Name = "fixed144";
			this.fixed144.HasWindow = false;
			this.table13.Add (this.fixed144);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed144]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed145 = new global::Gtk.Fixed ();
			this.fixed145.Name = "fixed145";
			this.fixed145.HasWindow = false;
			this.table13.Add (this.fixed145);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed145]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed146 = new global::Gtk.Fixed ();
			this.fixed146.Name = "fixed146";
			this.fixed146.HasWindow = false;
			this.table13.Add (this.fixed146);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed146]));
			w21.LeftAttach = ((uint)(3));
			w21.RightAttach = ((uint)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed147 = new global::Gtk.Fixed ();
			this.fixed147.Name = "fixed147";
			this.fixed147.HasWindow = false;
			this.table13.Add (this.fixed147);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed147]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed148 = new global::Gtk.Fixed ();
			this.fixed148.Name = "fixed148";
			this.fixed148.HasWindow = false;
			this.table13.Add (this.fixed148);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed148]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed149 = new global::Gtk.Fixed ();
			this.fixed149.Name = "fixed149";
			this.fixed149.HasWindow = false;
			this.table13.Add (this.fixed149);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed149]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed150 = new global::Gtk.Fixed ();
			this.fixed150.Name = "fixed150";
			this.fixed150.HasWindow = false;
			this.table13.Add (this.fixed150);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed150]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(3));
			w25.RightAttach = ((uint)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed151 = new global::Gtk.Fixed ();
			this.fixed151.Name = "fixed151";
			this.fixed151.HasWindow = false;
			this.table13.Add (this.fixed151);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed151]));
			w26.LeftAttach = ((uint)(4));
			w26.RightAttach = ((uint)(5));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed152 = new global::Gtk.Fixed ();
			this.fixed152.Name = "fixed152";
			this.fixed152.HasWindow = false;
			this.table13.Add (this.fixed152);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed152]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.LeftAttach = ((uint)(4));
			w27.RightAttach = ((uint)(5));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed153 = new global::Gtk.Fixed ();
			this.fixed153.Name = "fixed153";
			this.fixed153.HasWindow = false;
			this.table13.Add (this.fixed153);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed153]));
			w28.TopAttach = ((uint)(2));
			w28.BottomAttach = ((uint)(3));
			w28.LeftAttach = ((uint)(3));
			w28.RightAttach = ((uint)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.fixed154 = new global::Gtk.Fixed ();
			this.fixed154.Name = "fixed154";
			this.fixed154.HasWindow = false;
			this.table13.Add (this.fixed154);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table13 [this.fixed154]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.LeftAttach = ((uint)(4));
			w29.RightAttach = ((uint)(5));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table13.Gtk.Table+TableChild
			this.labelMsg2 = new global::Gtk.Label ();
			this.labelMsg2.Name = "labelMsg2";
			this.labelMsg2.LabelProp = global::Mono.Unix.Catalog.GetString ("Gracias por su visita!");
			this.table13.Add (this.labelMsg2);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table13 [this.labelMsg2]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.LeftAttach = ((uint)(2));
			w30.RightAttach = ((uint)(3));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table13);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table13]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table14 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table14.Name = "table14";
			this.table14.RowSpacing = ((uint)(6));
			this.table14.ColumnSpacing = ((uint)(6));
			// Container child table14.Gtk.Table+TableChild
			this.botonAceptar = new global::Gtk.Button ();
			this.botonAceptar.CanFocus = true;
			this.botonAceptar.Name = "botonAceptar";
			this.botonAceptar.UseUnderline = true;
			// Container child botonAceptar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w32 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w33 = new global::Gtk.HBox ();
			w33.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w34 = new global::Gtk.Image ();
			w34.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w33.Add (w34);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w36 = new global::Gtk.Label ();
			w36.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
			w36.UseUnderline = true;
			w33.Add (w36);
			w32.Add (w33);
			this.botonAceptar.Add (w32);
			this.table14.Add (this.botonAceptar);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table14 [this.botonAceptar]));
			w40.TopAttach = ((uint)(1));
			w40.BottomAttach = ((uint)(2));
			w40.LeftAttach = ((uint)(2));
			w40.RightAttach = ((uint)(3));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed155 = new global::Gtk.Fixed ();
			this.fixed155.Name = "fixed155";
			this.fixed155.HasWindow = false;
			this.table14.Add (this.fixed155);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed155]));
			w41.LeftAttach = ((uint)(2));
			w41.RightAttach = ((uint)(3));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed156 = new global::Gtk.Fixed ();
			this.fixed156.Name = "fixed156";
			this.fixed156.HasWindow = false;
			this.table14.Add (this.fixed156);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed156]));
			w42.LeftAttach = ((uint)(1));
			w42.RightAttach = ((uint)(2));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed157 = new global::Gtk.Fixed ();
			this.fixed157.Name = "fixed157";
			this.fixed157.HasWindow = false;
			this.table14.Add (this.fixed157);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed157]));
			w43.TopAttach = ((uint)(1));
			w43.BottomAttach = ((uint)(2));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed158 = new global::Gtk.Fixed ();
			this.fixed158.Name = "fixed158";
			this.fixed158.HasWindow = false;
			this.table14.Add (this.fixed158);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed158]));
			w44.TopAttach = ((uint)(1));
			w44.BottomAttach = ((uint)(2));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed159 = new global::Gtk.Fixed ();
			this.fixed159.Name = "fixed159";
			this.fixed159.HasWindow = false;
			this.table14.Add (this.fixed159);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed159]));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table14);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table14]));
			w46.Position = 4;
			w46.Expand = false;
			w46.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 513;
			this.DefaultHeight = 184;
			this.Show ();
			this.botonAceptar.Clicked += new global::System.EventHandler (this.OnBotonAceptarClicked);
		}
	}
}
