
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoCafeteria
{
	public partial class AlmuerzoCompleto
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label labelAlmuerzoCompleto;
		private global::Gtk.Fixed fixed106;
		private global::Gtk.Fixed fixed107;
		private global::Gtk.Fixed fixed108;
		private global::Gtk.Table table14;
		private global::Gtk.ComboBox comboboxBebida;
		private global::Gtk.ComboBox comboboxBocadillo;
		private global::Gtk.ComboBox comboboxCafe;
		private global::Gtk.ComboBox comboboxPrecio;
		private global::Gtk.Fixed fixed109;
		private global::Gtk.Fixed fixed110;
		private global::Gtk.Fixed fixed111;
		private global::Gtk.Fixed fixed112;
		private global::Gtk.Fixed fixed113;
		private global::Gtk.Fixed fixed114;
		private global::Gtk.Fixed fixed115;
		private global::Gtk.Fixed fixed116;
		private global::Gtk.Label labelBebida;
		private global::Gtk.Label labelBocadillo;
		private global::Gtk.Label labelCafe;
		private global::Gtk.Label labelCantidad;
		private global::Gtk.Label labelPrecio;
		private global::Gtk.SpinButton spinbuttonCantidad;
		private global::Gtk.Fixed fixed117;
		private global::Gtk.Fixed fixed118;
		private global::Gtk.Table table15;
		private global::Gtk.Button botonAceptar;
		private global::Gtk.Button botonAtras;
		private global::Gtk.Button botonCancelar;
		private global::Gtk.Fixed fixed119;
		private global::Gtk.Fixed fixed120;
		private global::Gtk.Fixed fixed121;
		private global::Gtk.Fixed fixed122;
		private global::Gtk.Fixed fixed123;
		private global::Gtk.Fixed fixed124;
		private global::Gtk.Fixed fixed125;
		private global::Gtk.Fixed fixed126;
		private global::Gtk.Fixed fixed127;
		private global::Gtk.Fixed fixed128;
		private global::Gtk.Fixed fixed129;
		private global::Gtk.Fixed fixed130;
		private global::Gtk.Fixed fixed131;
		private global::Gtk.Fixed fixed132;
		private global::Gtk.Fixed fixed133;
		private global::Gtk.Fixed fixed134;
		private global::Gtk.Fixed fixed135;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoCafeteria.AlmuerzoCompleto
			this.Name = "ProyectoCafeteria.AlmuerzoCompleto";
			this.Title = global::Mono.Unix.Catalog.GetString ("AlmuerzoCompleto");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoCafeteria.AlmuerzoCompleto.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.labelAlmuerzoCompleto = new global::Gtk.Label ();
			this.labelAlmuerzoCompleto.Name = "labelAlmuerzoCompleto";
			this.labelAlmuerzoCompleto.LabelProp = global::Mono.Unix.Catalog.GetString ("label25");
			this.vbox7.Add (this.labelAlmuerzoCompleto);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.labelAlmuerzoCompleto]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.fixed106 = new global::Gtk.Fixed ();
			this.fixed106.Name = "fixed106";
			this.fixed106.HasWindow = false;
			this.vbox7.Add (this.fixed106);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed106]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.fixed107 = new global::Gtk.Fixed ();
			this.fixed107.Name = "fixed107";
			this.fixed107.HasWindow = false;
			this.vbox7.Add (this.fixed107);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed107]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.fixed108 = new global::Gtk.Fixed ();
			this.fixed108.Name = "fixed108";
			this.fixed108.HasWindow = false;
			this.vbox7.Add (this.fixed108);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed108]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table14 = new global::Gtk.Table (((uint)(2)), ((uint)(9)), false);
			this.table14.Name = "table14";
			this.table14.RowSpacing = ((uint)(6));
			this.table14.ColumnSpacing = ((uint)(6));
			// Container child table14.Gtk.Table+TableChild
			this.comboboxBebida = global::Gtk.ComboBox.NewText ();
			this.comboboxBebida.Name = "comboboxBebida";
			this.table14.Add (this.comboboxBebida);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table14 [this.comboboxBebida]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.comboboxBocadillo = global::Gtk.ComboBox.NewText ();
			this.comboboxBocadillo.Name = "comboboxBocadillo";
			this.table14.Add (this.comboboxBocadillo);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table14 [this.comboboxBocadillo]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.comboboxCafe = global::Gtk.ComboBox.NewText ();
			this.comboboxCafe.Name = "comboboxCafe";
			this.table14.Add (this.comboboxCafe);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table14 [this.comboboxCafe]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(4));
			w7.RightAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.comboboxPrecio = global::Gtk.ComboBox.NewText ();
			this.comboboxPrecio.Name = "comboboxPrecio";
			this.table14.Add (this.comboboxPrecio);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table14 [this.comboboxPrecio]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(6));
			w8.RightAttach = ((uint)(7));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed109 = new global::Gtk.Fixed ();
			this.fixed109.Name = "fixed109";
			this.fixed109.HasWindow = false;
			this.table14.Add (this.fixed109);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed109]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed110 = new global::Gtk.Fixed ();
			this.fixed110.Name = "fixed110";
			this.fixed110.HasWindow = false;
			this.table14.Add (this.fixed110);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed110]));
			w10.LeftAttach = ((uint)(3));
			w10.RightAttach = ((uint)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed111 = new global::Gtk.Fixed ();
			this.fixed111.Name = "fixed111";
			this.fixed111.HasWindow = false;
			this.table14.Add (this.fixed111);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed111]));
			w11.LeftAttach = ((uint)(5));
			w11.RightAttach = ((uint)(6));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed112 = new global::Gtk.Fixed ();
			this.fixed112.Name = "fixed112";
			this.fixed112.HasWindow = false;
			this.table14.Add (this.fixed112);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed112]));
			w12.LeftAttach = ((uint)(7));
			w12.RightAttach = ((uint)(8));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed113 = new global::Gtk.Fixed ();
			this.fixed113.Name = "fixed113";
			this.fixed113.HasWindow = false;
			this.table14.Add (this.fixed113);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed113]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed114 = new global::Gtk.Fixed ();
			this.fixed114.Name = "fixed114";
			this.fixed114.HasWindow = false;
			this.table14.Add (this.fixed114);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed114]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(3));
			w14.RightAttach = ((uint)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed115 = new global::Gtk.Fixed ();
			this.fixed115.Name = "fixed115";
			this.fixed115.HasWindow = false;
			this.table14.Add (this.fixed115);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed115]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(5));
			w15.RightAttach = ((uint)(6));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.fixed116 = new global::Gtk.Fixed ();
			this.fixed116.Name = "fixed116";
			this.fixed116.HasWindow = false;
			this.table14.Add (this.fixed116);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table14 [this.fixed116]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(7));
			w16.RightAttach = ((uint)(8));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.labelBebida = new global::Gtk.Label ();
			this.labelBebida.Name = "labelBebida";
			this.labelBebida.LabelProp = global::Mono.Unix.Catalog.GetString ("Bebida");
			this.table14.Add (this.labelBebida);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table14 [this.labelBebida]));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.labelBocadillo = new global::Gtk.Label ();
			this.labelBocadillo.Name = "labelBocadillo";
			this.labelBocadillo.LabelProp = global::Mono.Unix.Catalog.GetString ("Bocadillo");
			this.table14.Add (this.labelBocadillo);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table14 [this.labelBocadillo]));
			w18.LeftAttach = ((uint)(2));
			w18.RightAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.labelCafe = new global::Gtk.Label ();
			this.labelCafe.Name = "labelCafe";
			this.labelCafe.LabelProp = global::Mono.Unix.Catalog.GetString ("Café");
			this.table14.Add (this.labelCafe);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table14 [this.labelCafe]));
			w19.LeftAttach = ((uint)(4));
			w19.RightAttach = ((uint)(5));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.labelCantidad = new global::Gtk.Label ();
			this.labelCantidad.Name = "labelCantidad";
			this.labelCantidad.LabelProp = global::Mono.Unix.Catalog.GetString ("Cantidad");
			this.table14.Add (this.labelCantidad);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table14 [this.labelCantidad]));
			w20.LeftAttach = ((uint)(8));
			w20.RightAttach = ((uint)(9));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.labelPrecio = new global::Gtk.Label ();
			this.labelPrecio.Name = "labelPrecio";
			this.labelPrecio.LabelProp = global::Mono.Unix.Catalog.GetString ("Precio");
			this.table14.Add (this.labelPrecio);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table14 [this.labelPrecio]));
			w21.LeftAttach = ((uint)(6));
			w21.RightAttach = ((uint)(7));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table14.Gtk.Table+TableChild
			this.spinbuttonCantidad = new global::Gtk.SpinButton (0, 100, 1);
			this.spinbuttonCantidad.CanFocus = true;
			this.spinbuttonCantidad.Name = "spinbuttonCantidad";
			this.spinbuttonCantidad.Adjustment.PageIncrement = 10;
			this.spinbuttonCantidad.ClimbRate = 1;
			this.spinbuttonCantidad.Numeric = true;
			this.table14.Add (this.spinbuttonCantidad);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table14 [this.spinbuttonCantidad]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(8));
			w22.RightAttach = ((uint)(9));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table14);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table14]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.fixed117 = new global::Gtk.Fixed ();
			this.fixed117.Name = "fixed117";
			this.fixed117.HasWindow = false;
			this.vbox7.Add (this.fixed117);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed117]));
			w24.Position = 5;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.fixed118 = new global::Gtk.Fixed ();
			this.fixed118.Name = "fixed118";
			this.fixed118.HasWindow = false;
			this.vbox7.Add (this.fixed118);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed118]));
			w25.Position = 6;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table15 = new global::Gtk.Table (((uint)(4)), ((uint)(5)), false);
			this.table15.Name = "table15";
			this.table15.RowSpacing = ((uint)(6));
			this.table15.ColumnSpacing = ((uint)(6));
			// Container child table15.Gtk.Table+TableChild
			this.botonAceptar = new global::Gtk.Button ();
			this.botonAceptar.CanFocus = true;
			this.botonAceptar.Name = "botonAceptar";
			this.botonAceptar.UseUnderline = true;
			// Container child botonAceptar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w26 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w27 = new global::Gtk.HBox ();
			w27.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w27.Add (w28);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w30 = new global::Gtk.Label ();
			w30.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
			w30.UseUnderline = true;
			w27.Add (w30);
			w26.Add (w27);
			this.botonAceptar.Add (w26);
			this.table15.Add (this.botonAceptar);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table15 [this.botonAceptar]));
			w34.TopAttach = ((uint)(3));
			w34.BottomAttach = ((uint)(4));
			w34.LeftAttach = ((uint)(3));
			w34.RightAttach = ((uint)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.botonAtras = new global::Gtk.Button ();
			this.botonAtras.CanFocus = true;
			this.botonAtras.Name = "botonAtras";
			this.botonAtras.UseUnderline = true;
			// Container child botonAtras.Gtk.Container+ContainerChild
			global::Gtk.Alignment w35 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w36 = new global::Gtk.HBox ();
			w36.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w37 = new global::Gtk.Image ();
			w37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-home", global::Gtk.IconSize.Menu);
			w36.Add (w37);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w39 = new global::Gtk.Label ();
			w39.LabelProp = global::Mono.Unix.Catalog.GetString ("Atrás");
			w39.UseUnderline = true;
			w36.Add (w39);
			w35.Add (w36);
			this.botonAtras.Add (w35);
			this.table15.Add (this.botonAtras);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table15 [this.botonAtras]));
			w43.TopAttach = ((uint)(3));
			w43.BottomAttach = ((uint)(4));
			w43.LeftAttach = ((uint)(2));
			w43.RightAttach = ((uint)(3));
			w43.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table15.Gtk.Table+TableChild
			this.botonCancelar = new global::Gtk.Button ();
			this.botonCancelar.CanFocus = true;
			this.botonCancelar.Name = "botonCancelar";
			this.botonCancelar.UseUnderline = true;
			// Container child botonCancelar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w44 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w45 = new global::Gtk.HBox ();
			w45.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w46 = new global::Gtk.Image ();
			w46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w45.Add (w46);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w48 = new global::Gtk.Label ();
			w48.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancelar");
			w48.UseUnderline = true;
			w45.Add (w48);
			w44.Add (w45);
			this.botonCancelar.Add (w44);
			this.table15.Add (this.botonCancelar);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table15 [this.botonCancelar]));
			w52.TopAttach = ((uint)(3));
			w52.BottomAttach = ((uint)(4));
			w52.LeftAttach = ((uint)(4));
			w52.RightAttach = ((uint)(5));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed119 = new global::Gtk.Fixed ();
			this.fixed119.Name = "fixed119";
			this.fixed119.HasWindow = false;
			this.table15.Add (this.fixed119);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed119]));
			w53.LeftAttach = ((uint)(4));
			w53.RightAttach = ((uint)(5));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed120 = new global::Gtk.Fixed ();
			this.fixed120.Name = "fixed120";
			this.fixed120.HasWindow = false;
			this.table15.Add (this.fixed120);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed120]));
			w54.LeftAttach = ((uint)(3));
			w54.RightAttach = ((uint)(4));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed121 = new global::Gtk.Fixed ();
			this.fixed121.Name = "fixed121";
			this.fixed121.HasWindow = false;
			this.table15.Add (this.fixed121);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed121]));
			w55.LeftAttach = ((uint)(2));
			w55.RightAttach = ((uint)(3));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed122 = new global::Gtk.Fixed ();
			this.fixed122.Name = "fixed122";
			this.fixed122.HasWindow = false;
			this.table15.Add (this.fixed122);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed122]));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed123 = new global::Gtk.Fixed ();
			this.fixed123.Name = "fixed123";
			this.fixed123.HasWindow = false;
			this.table15.Add (this.fixed123);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed123]));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed124 = new global::Gtk.Fixed ();
			this.fixed124.Name = "fixed124";
			this.fixed124.HasWindow = false;
			this.table15.Add (this.fixed124);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed124]));
			w58.TopAttach = ((uint)(1));
			w58.BottomAttach = ((uint)(2));
			w58.LeftAttach = ((uint)(4));
			w58.RightAttach = ((uint)(5));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed125 = new global::Gtk.Fixed ();
			this.fixed125.Name = "fixed125";
			this.fixed125.HasWindow = false;
			this.table15.Add (this.fixed125);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed125]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(3));
			w59.RightAttach = ((uint)(4));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed126 = new global::Gtk.Fixed ();
			this.fixed126.Name = "fixed126";
			this.fixed126.HasWindow = false;
			this.table15.Add (this.fixed126);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed126]));
			w60.TopAttach = ((uint)(1));
			w60.BottomAttach = ((uint)(2));
			w60.LeftAttach = ((uint)(2));
			w60.RightAttach = ((uint)(3));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed127 = new global::Gtk.Fixed ();
			this.fixed127.Name = "fixed127";
			this.fixed127.HasWindow = false;
			this.table15.Add (this.fixed127);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed127]));
			w61.TopAttach = ((uint)(1));
			w61.BottomAttach = ((uint)(2));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed128 = new global::Gtk.Fixed ();
			this.fixed128.Name = "fixed128";
			this.fixed128.HasWindow = false;
			this.table15.Add (this.fixed128);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed128]));
			w62.TopAttach = ((uint)(1));
			w62.BottomAttach = ((uint)(2));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed129 = new global::Gtk.Fixed ();
			this.fixed129.Name = "fixed129";
			this.fixed129.HasWindow = false;
			this.table15.Add (this.fixed129);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed129]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.LeftAttach = ((uint)(4));
			w63.RightAttach = ((uint)(5));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed130 = new global::Gtk.Fixed ();
			this.fixed130.Name = "fixed130";
			this.fixed130.HasWindow = false;
			this.table15.Add (this.fixed130);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed130]));
			w64.TopAttach = ((uint)(2));
			w64.BottomAttach = ((uint)(3));
			w64.LeftAttach = ((uint)(3));
			w64.RightAttach = ((uint)(4));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed131 = new global::Gtk.Fixed ();
			this.fixed131.Name = "fixed131";
			this.fixed131.HasWindow = false;
			this.table15.Add (this.fixed131);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed131]));
			w65.TopAttach = ((uint)(2));
			w65.BottomAttach = ((uint)(3));
			w65.LeftAttach = ((uint)(2));
			w65.RightAttach = ((uint)(3));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed132 = new global::Gtk.Fixed ();
			this.fixed132.Name = "fixed132";
			this.fixed132.HasWindow = false;
			this.table15.Add (this.fixed132);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed132]));
			w66.TopAttach = ((uint)(2));
			w66.BottomAttach = ((uint)(3));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed133 = new global::Gtk.Fixed ();
			this.fixed133.Name = "fixed133";
			this.fixed133.HasWindow = false;
			this.table15.Add (this.fixed133);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed133]));
			w67.TopAttach = ((uint)(2));
			w67.BottomAttach = ((uint)(3));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed134 = new global::Gtk.Fixed ();
			this.fixed134.Name = "fixed134";
			this.fixed134.HasWindow = false;
			this.table15.Add (this.fixed134);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed134]));
			w68.TopAttach = ((uint)(3));
			w68.BottomAttach = ((uint)(4));
			w68.LeftAttach = ((uint)(1));
			w68.RightAttach = ((uint)(2));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.fixed135 = new global::Gtk.Fixed ();
			this.fixed135.Name = "fixed135";
			this.fixed135.HasWindow = false;
			this.table15.Add (this.fixed135);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table15 [this.fixed135]));
			w69.TopAttach = ((uint)(3));
			w69.BottomAttach = ((uint)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table15);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table15]));
			w70.Position = 7;
			w70.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 234;
			this.Show ();
			this.botonCancelar.Clicked += new global::System.EventHandler (this.OnBotonCancelarClicked);
			this.botonAtras.Clicked += new global::System.EventHandler (this.OnBotonAtrasClicked);
			this.botonAceptar.Clicked += new global::System.EventHandler (this.OnBotonAceptarClicked);
		}
	}
}
