
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoCafeteria
{
	public partial class LlenarTreeViewBebidas
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoCafeteria.LlenarTreeViewBebidas
			this.Name = "ProyectoCafeteria.LlenarTreeViewBebidas";
			this.Title = global::Mono.Unix.Catalog.GetString ("LlenarTreeViewBebidas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
