
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoCafeteria
{
	public partial class AñadirNumPersonas
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Fixed fixed39;
		private global::Gtk.Table table3;
		private global::Gtk.Fixed fixed29;
		private global::Gtk.Fixed fixed30;
		private global::Gtk.Fixed fixed31;
		private global::Gtk.Fixed fixed32;
		private global::Gtk.Fixed fixed33;
		private global::Gtk.Fixed fixed34;
		private global::Gtk.Fixed fixed35;
		private global::Gtk.Fixed fixed36;
		private global::Gtk.Fixed fixed37;
		private global::Gtk.Fixed fixed38;
		private global::Gtk.Label labelMensaje;
		private global::Gtk.SpinButton spinNumPersonas;
		private global::Gtk.Fixed fixed40;
		private global::Gtk.Table table4;
		private global::Gtk.Button botonAceptar;
		private global::Gtk.Button botonCancelar;
		private global::Gtk.Fixed fixed19;
		private global::Gtk.Fixed fixed20;
		private global::Gtk.Fixed fixed21;
		private global::Gtk.Fixed fixed22;
		private global::Gtk.Fixed fixed23;
		private global::Gtk.Fixed fixed24;
		private global::Gtk.Fixed fixed25;
		private global::Gtk.Fixed fixed26;
		private global::Gtk.Fixed fixed27;
		private global::Gtk.Fixed fixed28;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoCafeteria.AñadirNumPersonas
			this.Name = "ProyectoCafeteria.AñadirNumPersonas";
			this.Title = global::Mono.Unix.Catalog.GetString ("añadirNumPersonas");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			// Container child ProyectoCafeteria.AñadirNumPersonas.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed39 = new global::Gtk.Fixed ();
			this.fixed39.Name = "fixed39";
			this.fixed39.HasWindow = false;
			this.vbox3.Add (this.fixed39);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed39]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.fixed29 = new global::Gtk.Fixed ();
			this.fixed29.Name = "fixed29";
			this.fixed29.HasWindow = false;
			this.table3.Add (this.fixed29);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed29]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(3));
			w2.RightAttach = ((uint)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed30 = new global::Gtk.Fixed ();
			this.fixed30.Name = "fixed30";
			this.fixed30.HasWindow = false;
			this.table3.Add (this.fixed30);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed30]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed31 = new global::Gtk.Fixed ();
			this.fixed31.Name = "fixed31";
			this.fixed31.HasWindow = false;
			this.table3.Add (this.fixed31);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed31]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed32 = new global::Gtk.Fixed ();
			this.fixed32.Name = "fixed32";
			this.fixed32.HasWindow = false;
			this.table3.Add (this.fixed32);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed32]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed33 = new global::Gtk.Fixed ();
			this.fixed33.Name = "fixed33";
			this.fixed33.HasWindow = false;
			this.table3.Add (this.fixed33);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed33]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed34 = new global::Gtk.Fixed ();
			this.fixed34.Name = "fixed34";
			this.fixed34.HasWindow = false;
			this.table3.Add (this.fixed34);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed34]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(3));
			w7.RightAttach = ((uint)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed35 = new global::Gtk.Fixed ();
			this.fixed35.Name = "fixed35";
			this.fixed35.HasWindow = false;
			this.table3.Add (this.fixed35);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed35]));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed36 = new global::Gtk.Fixed ();
			this.fixed36.Name = "fixed36";
			this.fixed36.HasWindow = false;
			this.table3.Add (this.fixed36);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed36]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed37 = new global::Gtk.Fixed ();
			this.fixed37.Name = "fixed37";
			this.fixed37.HasWindow = false;
			this.table3.Add (this.fixed37);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed37]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed38 = new global::Gtk.Fixed ();
			this.fixed38.Name = "fixed38";
			this.fixed38.HasWindow = false;
			this.table3.Add (this.fixed38);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed38]));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelMensaje = new global::Gtk.Label ();
			this.labelMensaje.Name = "labelMensaje";
			this.labelMensaje.LabelProp = global::Mono.Unix.Catalog.GetString ("Por favor,\nindique el número de personas,\npara facilitarles mesa.\nGracias.");
			this.table3.Add (this.labelMensaje);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelMensaje]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinNumPersonas = new global::Gtk.SpinButton (0, 100, 1);
			this.spinNumPersonas.CanFocus = true;
			this.spinNumPersonas.Name = "spinNumPersonas";
			this.spinNumPersonas.Adjustment.PageIncrement = 10;
			this.spinNumPersonas.ClimbRate = 1;
			this.spinNumPersonas.Numeric = true;
			this.table3.Add (this.spinNumPersonas);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinNumPersonas]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table3]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed40 = new global::Gtk.Fixed ();
			this.fixed40.Name = "fixed40";
			this.fixed40.HasWindow = false;
			this.vbox3.Add (this.fixed40);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed40]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.botonAceptar = new global::Gtk.Button ();
			this.botonAceptar.CanFocus = true;
			this.botonAceptar.Name = "botonAceptar";
			this.botonAceptar.UseUnderline = true;
			// Container child botonAceptar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w16 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w17 = new global::Gtk.HBox ();
			w17.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w18 = new global::Gtk.Image ();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w17.Add (w18);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w20 = new global::Gtk.Label ();
			w20.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
			w20.UseUnderline = true;
			w17.Add (w20);
			w16.Add (w17);
			this.botonAceptar.Add (w16);
			this.table4.Add (this.botonAceptar);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table4 [this.botonAceptar]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.botonCancelar = new global::Gtk.Button ();
			this.botonCancelar.CanFocus = true;
			this.botonCancelar.Name = "botonCancelar";
			this.botonCancelar.UseUnderline = true;
			// Container child botonCancelar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w25 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w26 = new global::Gtk.HBox ();
			w26.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w27 = new global::Gtk.Image ();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w26.Add (w27);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w29 = new global::Gtk.Label ();
			w29.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancelar");
			w29.UseUnderline = true;
			w26.Add (w29);
			w25.Add (w26);
			this.botonCancelar.Add (w25);
			this.table4.Add (this.botonCancelar);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table4 [this.botonCancelar]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.LeftAttach = ((uint)(3));
			w33.RightAttach = ((uint)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed19 = new global::Gtk.Fixed ();
			this.fixed19.Name = "fixed19";
			this.fixed19.HasWindow = false;
			this.table4.Add (this.fixed19);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed19]));
			w34.TopAttach = ((uint)(2));
			w34.BottomAttach = ((uint)(3));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed20 = new global::Gtk.Fixed ();
			this.fixed20.Name = "fixed20";
			this.fixed20.HasWindow = false;
			this.table4.Add (this.fixed20);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed20]));
			w35.TopAttach = ((uint)(2));
			w35.BottomAttach = ((uint)(3));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed21 = new global::Gtk.Fixed ();
			this.fixed21.Name = "fixed21";
			this.fixed21.HasWindow = false;
			this.table4.Add (this.fixed21);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed21]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.LeftAttach = ((uint)(3));
			w36.RightAttach = ((uint)(4));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed22 = new global::Gtk.Fixed ();
			this.fixed22.Name = "fixed22";
			this.fixed22.HasWindow = false;
			this.table4.Add (this.fixed22);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed22]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.LeftAttach = ((uint)(2));
			w37.RightAttach = ((uint)(3));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed23 = new global::Gtk.Fixed ();
			this.fixed23.Name = "fixed23";
			this.fixed23.HasWindow = false;
			this.table4.Add (this.fixed23);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed23]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed24 = new global::Gtk.Fixed ();
			this.fixed24.Name = "fixed24";
			this.fixed24.HasWindow = false;
			this.table4.Add (this.fixed24);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed24]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed25 = new global::Gtk.Fixed ();
			this.fixed25.Name = "fixed25";
			this.fixed25.HasWindow = false;
			this.table4.Add (this.fixed25);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed25]));
			w40.LeftAttach = ((uint)(3));
			w40.RightAttach = ((uint)(4));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed26 = new global::Gtk.Fixed ();
			this.fixed26.Name = "fixed26";
			this.fixed26.HasWindow = false;
			this.table4.Add (this.fixed26);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed26]));
			w41.LeftAttach = ((uint)(2));
			w41.RightAttach = ((uint)(3));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed27 = new global::Gtk.Fixed ();
			this.fixed27.Name = "fixed27";
			this.fixed27.HasWindow = false;
			this.table4.Add (this.fixed27);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed27]));
			w42.LeftAttach = ((uint)(1));
			w42.RightAttach = ((uint)(2));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.fixed28 = new global::Gtk.Fixed ();
			this.fixed28.Name = "fixed28";
			this.fixed28.HasWindow = false;
			this.table4.Add (this.fixed28);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed28]));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table4]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 169;
			this.Show ();
			this.botonCancelar.Clicked += new global::System.EventHandler (this.OnBotonCancelarClicked);
			this.botonAceptar.Clicked += new global::System.EventHandler (this.OnBotonAceptarClicked);
		}
	}
}
